namespace: wooglife

cronjob:
  name: tweeter
  image: ghcr.io/woog-life/tweeter:__TAG__
  imagePullPolicy: IfNotPresent
  schedule: "1 */2 * * *"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: tweeter
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

configmap:
  name: tweeter-config
  backendPath: "lake/{}/temperature"
  backendUrl: "http://backend:8080"
  mastodon:
    instanceUrl: "https://mastodon.social"

secret:
  mastodon:
    name: tweeter-mastodon
    accessToken: __MASTODON_ACCESS_TOKEN__
