apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.twitter.name }}
  namespace: {{ .Values.namespace }}
data:
  ACCESS_TOKEN: "{{ .Values.secret.twitter.accessToken }}"
  ACCESS_TOKEN_SECRET: "{{ .Values.secret.twitter.accessTokenSecret }}"
  CONSUMER_KEY: "{{ .Values.secret.twitter.consumerKey }}"
  CONSUMER_SECRET: "{{ .Values.secret.twitter.consumerSecret }}"
