name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/tweeter:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/woog-life/tweeter:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: [build_push_docker, lint]
    steps:
      - uses: actions/checkout@v3
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - run: sed -i -e "s#__TELEGRAM_TOKEN_ERROR__#${{ secrets.TELEGRAM_TOKEN_ERROR }}#g" values.yaml
      - run: sed -i -e "s/__CONSUMER_KEY__/${{ secrets.TWITTER_CONSUMER_KEY }}/g" values.yaml
      - run: sed -i -e "s/__CONSUMER_SECRET__/${{ secrets.TWITTER_CONSUMER_SECRET }}/g" values.yaml
      - run: sed -i -e "s/__ACCESS_TOKEN__/${{ secrets.TWITTER_ACCESS_TOKEN }}/g" values.yaml
      - run: sed -i -e "s/__ACCESS_TOKEN_SECRET__/${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}/g" values.yaml
      - run: sed -i -e "s/__PAGERDUTY_ROUTING_KEY__/${{ secrets.PAGERDUTY_ROUTING_KEY }}/g" values.yaml
      - run: sed -i -e "s/__MASTODON_ACCESS_TOKEN__/${{ secrets.MASTODON_ACCESS_TOKEN }}/g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade tweeter . --install --namespace=wooglife --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
