name: Build image

on:
  push:
    branches:
      - '!master'

jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/woog-life/tweeter:${GITHUB_SHA} .
